/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        combo.addItem("Voltaje (V)");
        combo.addItem("Corriente (A)");
        combo.addItem("Resistencia (Ω)");
        combo.setUI(ComboBox.createUI(combo));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCorriente = new javax.swing.JLabel();
        txtResistencia = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        txtD1 = new javax.swing.JTextField();
        txtD2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        txtRespuesta = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        gif = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1040, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorriente.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtCorriente.setForeground(new java.awt.Color(255, 255, 255));
        txtCorriente.setText("Corriente");
        jPanel1.add(txtCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        txtResistencia.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtResistencia.setForeground(new java.awt.Color(255, 255, 255));
        txtResistencia.setText("Resistencia");
        jPanel1.add(txtResistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        txtResultado.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.setText("Resultado");
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));
        txtResultado.getAccessibleContext().setAccessibleParent(this);

        txtD1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtD1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtD1.setBorder(null);
        txtD1.setCaretColor(new java.awt.Color(102, 102, 102));
        txtD1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtD1.setSelectionColor(new java.awt.Color(83, 124, 164));
        txtD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD1ActionPerformed(evt);
            }
        });
        txtD1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtD1KeyTyped(evt);
            }
        });
        jPanel1.add(txtD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 180, 30));

        txtD2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtD2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtD2.setBorder(null);
        txtD2.setCaretColor(new java.awt.Color(102, 102, 102));
        txtD2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtD2.setSelectionColor(new java.awt.Color(83, 124, 164));
        txtD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD2ActionPerformed(evt);
            }
        });
        txtD2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtD2KeyTyped(evt);
            }
        });
        jPanel1.add(txtD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 180, 30));
        txtD2.getAccessibleContext().setAccessibleParent(this);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Qué deseas calcular?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        combo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        combo.setBorder(null);
        combo.setFocusable(false);
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 170, 30));
        combo.getAccessibleContext().setAccessibleParent(this);

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btncalcular.png"))); // NOI18N
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.setFocusPainted(false);
        btnCalcular.setPreferredSize(new java.awt.Dimension(138, 32));
        btnCalcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btncalcularHover.png"))); // NOI18N
        btnCalcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btncalcularHover.png"))); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 130, 30));

        txtRespuesta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 260, 30));
        txtRespuesta.getAccessibleContext().setAccessibleParent(this);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnmenu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnmenuHover.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnmenuHover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/diododirecta32kg.gif"))); // NOI18N
        gif.setToolTipText("");
        gif.setAlignmentX(0.5F);
        jPanel1.add(gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 290, 240));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoCALCULADORAP.png"))); // NOI18N
        Fondo.setAlignmentX(0.5F);
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if (txtD1.getText().isEmpty() || txtD2.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Favor de llenar todos los campos");
        }else{
            double num1 = Double.parseDouble(txtD1.getText());
            double num2 = Double.parseDouble(txtD2.getText());
            double respuesta = 0;
            String valor,medida;
            valor  = "";
            medida = "";

            String op = combo.getSelectedItem().toString();

            if (op.equalsIgnoreCase("voltaje (V)")){
                respuesta = num1 * num2;
                valor  = "Su voltaje es de ";
                medida = "V";
            }

            if (op.equalsIgnoreCase("corriente (A)")){
                respuesta = num1 / num2;
                valor  = "Su corriente es de ";
                medida = "A";
            }

            if (op.equalsIgnoreCase("resistencia (Ω)")){
                respuesta = num1 / num2;
                valor  = "Su resistencia es de ";
                medida = "Ω";
            }

            txtRespuesta.setText(valor + (double)Math.round(respuesta*100d)/100 + " " + medida);
            txtD1.setText("");
            txtD2.setText("");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        String op = combo.getSelectedItem().toString();

        if (op.equalsIgnoreCase("voltaje (V)")){
            txtCorriente.setText("Corriente");
            txtResistencia.setText("Resistencia");
            txtRespuesta.setText("");
        }

        if (op.equalsIgnoreCase("corriente (A)")){
            txtCorriente.setText("Voltaje");
            txtResistencia.setText("Resistencia");
            txtRespuesta.setText("");           
        }

        if (op.equalsIgnoreCase("resistencia (Ω)")){
            txtCorriente.setText("Voltaje");
            txtResistencia.setText("Corriente");
            txtRespuesta.setText("");
        }
    }//GEN-LAST:event_comboActionPerformed

    private void txtD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtD1ActionPerformed

    private void txtD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtD2ActionPerformed

    private void txtD1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtD1KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.' && evt.getKeyChar()!='-'){
            evt.consume();
        }
        if (evt.getKeyChar()=='.' && txtD1.getText().contains(".")){
            evt.consume();
        }
        
        if (evt.getKeyChar()=='-' && txtD1.getText().contains("-")){
            evt.consume();
        } 
    }//GEN-LAST:event_txtD1KeyTyped

    private void txtD2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtD2KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.' && evt.getKeyChar()!='-'){
            evt.consume();
        }
        if (evt.getKeyChar()=='.' && txtD2.getText().contains(".")){
            evt.consume();
        }
        
        if (evt.getKeyChar()=='-' && txtD2.getText().contains("-")){
            evt.consume();
        } 
    }//GEN-LAST:event_txtD2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio in = new Inicio();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel gif;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCorriente;
    private javax.swing.JTextField txtD1;
    private javax.swing.JTextField txtD2;
    private javax.swing.JLabel txtResistencia;
    private javax.swing.JLabel txtRespuesta;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
