/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Conversion extends javax.swing.JFrame {

    /**
     * Creates new form Conversion
     */
    public Conversion() {
        initComponents();
        comboDatos3.addItem("Tensión");
        comboDatos3.addItem("Corriente");
        comboDatos3.addItem("Resistencia");
        comboDatos1.setUI(ComboBox.createUI(comboDatos1));
        comboDatos2.setUI(ComboBox.createUI(comboDatos2));
        comboDatos3.setUI(ComboBox.createUI(comboDatos3));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDatos = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboDatos1 = new javax.swing.JComboBox<>();
        comboDatos2 = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboDatos3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDatos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDatos.setBorder(null);
        txtDatos.setCaretColor(new java.awt.Color(102, 102, 102));
        txtDatos.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtDatos.setSelectionColor(new java.awt.Color(83, 124, 164));
        txtDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatosActionPerformed(evt);
            }
        });
        txtDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatosKeyTyped(evt);
            }
        });
        jPanel1.add(txtDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 170, 30));

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setBorder(null);
        txtResultado.setCaretColor(new java.awt.Color(102, 102, 102));
        txtResultado.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtResultado.setSelectionColor(new java.awt.Color(83, 124, 164));
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        comboDatos1.setBorder(null);
        jPanel1.add(comboDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 170, 30));

        comboDatos2.setBorder(null);
        jPanel1.add(comboDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 170, 30));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btncalcular.png"))); // NOI18N
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCalcular.setFocusPainted(false);
        btnCalcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btncalcularHover.png"))); // NOI18N
        btnCalcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btncalcularHover.png"))); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoría de unidades de medida");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        comboDatos3.setBorder(null);
        comboDatos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDatos3ActionPerformed(evt);
            }
        });
        jPanel1.add(comboDatos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 170, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnmenu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnmenuHover.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnmenuHover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoCONVERTIDOR.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatosKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.' && evt.getKeyChar()!='-'){
            evt.consume();
        }
        if (evt.getKeyChar()=='.' && txtDatos.getText().contains(".")){
            evt.consume();
        }

        if (evt.getKeyChar()=='-' && txtDatos.getText().contains("-")){
            evt.consume();
        }
    }//GEN-LAST:event_txtDatosKeyTyped

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (txtDatos.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Favor de llenar todos los campos");
        }else{
            double num1 = Double.parseDouble(txtDatos.getText());
            double k = 0.001;
            double m = 1000;
            double l = 1000000;
            double respuesta = 0;

            String op  = comboDatos1.getSelectedItem().toString();
            String op2 = comboDatos2.getSelectedItem().toString();

            if (op.equalsIgnoreCase("kilovoltio (kV)")){
                respuesta = num1 / k;
            }

            if (op.equalsIgnoreCase("milívoltio (mV)")){
                respuesta = num1 / m;
            }

            if (op.equalsIgnoreCase("kiloamperio (kA)")){
                respuesta = num1 / k;
            }

            if (op.equalsIgnoreCase("milíamperio (mA)")){
                respuesta = num1 / m;
            }

            //RESISTENCIA
            if (op.equalsIgnoreCase("kiloohmio (kΩ)") && op2.equalsIgnoreCase("ohmio (Ω)")){
                respuesta = num1 / k;
            }

            if (op.equalsIgnoreCase("kiloohmio (kΩ)") && op2.equalsIgnoreCase("kiloohmio (kΩ)")){
                respuesta = num1 / 1;
            }

            if (op.equalsIgnoreCase("kiloohmio (kΩ)") && op2.equalsIgnoreCase("milíohmio (mΩ)")){
                respuesta = num1 * l;
            }
            //MILIOHMIOS
            if (op.equalsIgnoreCase("milíohmio (mΩ)") && op2.equalsIgnoreCase("ohmio (Ω)")){
                respuesta = num1 / m;
            }

            if (op.equalsIgnoreCase("milíohmio (mΩ)") && op2.equalsIgnoreCase("kiloohmio (kΩ)")){
                respuesta = num1 * 0.000001;
            }

            if (op.equalsIgnoreCase("milíohmio (mΩ)") && op2.equalsIgnoreCase("milíohmio (mΩ)")){
                respuesta = num1 / 1;
            }

            //OHMIOS
            if (op.equalsIgnoreCase("ohmio (Ω)") && op2.equalsIgnoreCase("ohmio (Ω)")){
                respuesta = num1 / 1;
            }

            if (op.equalsIgnoreCase("ohmio (Ω)") && op2.equalsIgnoreCase("kiloohmio (kΩ)")){
                respuesta = num1 * k;
            }

            if (op.equalsIgnoreCase("ohmio (Ω)") && op2.equalsIgnoreCase("milíohmio (mΩ)")){
                respuesta = num1 * m;
            }

            txtResultado.setText(""+respuesta);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void comboDatos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDatos3ActionPerformed

        String op = comboDatos3.getSelectedItem().toString();

        switch(op){
            case "Tensión":
            comboDatos1.removeAllItems();
            comboDatos2.removeAllItems();
            comboDatos1.addItem("kilovoltio (kV)");
            comboDatos1.addItem("milívoltio (mV)");
            comboDatos2.addItem("voltio (V)");
            txtResultado.setText("");
            break;

            case "Corriente":
            comboDatos1.removeAllItems();
            comboDatos2.removeAllItems();
            comboDatos1.addItem("kiloamperio (kA)");
            comboDatos1.addItem("milíamperio (mA)");
            comboDatos2.addItem("Amperio (A)");
            txtResultado.setText("");
            break;

            case "Resistencia":
            comboDatos1.removeAllItems();
            comboDatos2.removeAllItems();
            comboDatos1.addItem("kiloohmio (kΩ)");
            comboDatos1.addItem("milíohmio (mΩ)");
            comboDatos1.addItem("ohmio (Ω)");

            comboDatos2.addItem("ohmio (Ω)");
            comboDatos2.addItem("kiloohmio (kΩ)");
            comboDatos2.addItem("milíohmio (mΩ)");
            txtResultado.setText("");
            break;
        }
    }//GEN-LAST:event_comboDatos3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio in = new Inicio();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> comboDatos1;
    private javax.swing.JComboBox<String> comboDatos2;
    private javax.swing.JComboBox<String> comboDatos3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDatos;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
