/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

/**
 *
 * @author Usuario
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        btnconceptos = new javax.swing.JButton();
        btnformula = new javax.swing.JButton();
        btnconversion = new javax.swing.JButton();
        btncalculadora = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        FondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(63, 105, 97));
        setResizable(false);
        setSize(new java.awt.Dimension(1040, 690));

        Fondo.setPreferredSize(new java.awt.Dimension(1040, 690));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnconceptos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B1.png"))); // NOI18N
        btnconceptos.setBorder(null);
        btnconceptos.setBorderPainted(false);
        btnconceptos.setContentAreaFilled(false);
        btnconceptos.setFocusPainted(false);
        btnconceptos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B1Hover.png"))); // NOI18N
        btnconceptos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B1Hover.png"))); // NOI18N
        btnconceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconceptosActionPerformed(evt);
            }
        });
        Fondo.add(btnconceptos, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 110, -1, -1));

        btnformula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B2.png"))); // NOI18N
        btnformula.setBorder(null);
        btnformula.setBorderPainted(false);
        btnformula.setContentAreaFilled(false);
        btnformula.setFocusPainted(false);
        btnformula.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B2Hover.png"))); // NOI18N
        btnformula.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B2Hover.png"))); // NOI18N
        btnformula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformulaActionPerformed(evt);
            }
        });
        Fondo.add(btnformula, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 220, -1, -1));

        btnconversion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B3.png"))); // NOI18N
        btnconversion.setBorder(null);
        btnconversion.setBorderPainted(false);
        btnconversion.setContentAreaFilled(false);
        btnconversion.setFocusPainted(false);
        btnconversion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B3Hover.png"))); // NOI18N
        btnconversion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B3Hover.png"))); // NOI18N
        btnconversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconversionActionPerformed(evt);
            }
        });
        Fondo.add(btnconversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 330, -1, -1));

        btncalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B4.png"))); // NOI18N
        btncalculadora.setBorder(null);
        btncalculadora.setBorderPainted(false);
        btncalculadora.setContentAreaFilled(false);
        btncalculadora.setFocusPainted(false);
        btncalculadora.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B4Hover.png"))); // NOI18N
        btncalculadora.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B4Hover.png"))); // NOI18N
        btncalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculadoraActionPerformed(evt);
            }
        });
        Fondo.add(btncalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 440, -1, -1));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B5.png"))); // NOI18N
        btnsalir.setBorder(null);
        btnsalir.setBorderPainted(false);
        btnsalir.setContentAreaFilled(false);
        btnsalir.setFocusPainted(false);
        btnsalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B5Hover.png"))); // NOI18N
        btnsalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B5Hover.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        Fondo.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 550, -1, -1));

        FondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background.png"))); // NOI18N
        Fondo.add(FondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnformulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformulaActionPerformed
        // TODO add your handling code here:
        Formula fom = new Formula();
        fom.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnformulaActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculadoraActionPerformed
        // TODO add your handling code here:
        Calculadora cal = new Calculadora();
        cal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncalculadoraActionPerformed

    private void btnconversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconversionActionPerformed
        // TODO add your handling code here:
        Conversion con = new Conversion();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnconversionActionPerformed

    private void btnconceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconceptosActionPerformed
        // TODO add your handling code here:
        Concepto con = new Concepto();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnconceptosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel FondoInicio;
    private javax.swing.JButton btncalculadora;
    private javax.swing.JButton btnconceptos;
    private javax.swing.JButton btnconversion;
    private javax.swing.JButton btnformula;
    private javax.swing.JButton btnsalir;
    // End of variables declaration//GEN-END:variables
}
